### ISSUE TITLE
Add Block Module to composer

### ISSUE THREAD

**Issue by divyasreem** [AsgardCms/Block#10]
How to access the block module, I just cloned that module inside existing module but unable to access the block module even tables are not getting created, please help me out. New to larval no idea how to proceed further.

**Comment by nWidart** [comment]
Add your permissions as explained in the documentation.

**Comment by divyasreem** [comment]
Have this permissions , what change I need to make

<?php

return [
    'block.blocks' => [
        'index',
        'create',
        'store',
        'edit',
        'update',
        'destroy',
    ],
];

**Comment by nWidart** [comment]
You need to give yourself the permissions via the GUI on the backend. 

Go to users > roles > admin. Then the permissions tab, and give the Admin role the permissions.

**Comment by divyasreem** [comment]
After doing that I can see the block menu but tables are not created

**Comment by nWidart** [comment]
did you read the readme file ? You need to migrate.

**Comment by nWidart** [comment]
Run `php artisan module:migrate Block`

**Comment by divyasreem** [comment]
https://github.com/AsgardCms/Block/blob/master/readme.md

**Comment by divyasreem** [comment]
now tables got created, Thanks a lot

I couldn't find this command in readme

**Comment by nWidart** [comment]
My bad, I thought this was explained on the readme, sorry 😄

**Comment by divyasreem** [comment]
Thanks a lot for your support

**Comment by nWidart** [comment]
The readme file has been updated by @mikemand 👍
