### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by ma8h7er** [AsgardCms/Block#15]
Thank you for good work
How can I use {!! Block::get('main-slider') !!} in the ckeditor it becomes that {!! Block::get(&#3 9;main-slider&# 39;) !!} when I save the page

**Comment by nWidart** [comment]
Hello,

It's currently not possible to add the block to a wysiwyg editor.

**Comment by nWidart** [comment]
Hello,

It is now possible to hook into the block creation and update process. The same is also possible when the block content is rendering.

You can find example for this in the tests
