### ISSUE TITLE
recursive  embed in a twig tag block

### ISSUE THREAD

**Issue by sgweb1** [AsgardCms/Block#19]
How to embed in a twig tag block for example the recursive call of another block
In block {!! Block :: get ('slider') !!} put {!! Block :: get ('test') !!}

i add ckeeditor
config.protectedSource.push( /{!![\s\S]*?!!}/g ); // Freemarker
 template return text value '{!! Block::get('test') !!}'

**Comment by nWidart** [comment]
Hello,

It is now possible to hook into the block creation and update process. The same is also possible when the block content is rendering.

You can find example for this in the tests
