### ISSUE TITLE
Installing Block Module error

### ISSUE THREAD

**Issue by ikashifullah** [AsgardCms/Block#20]
Installing Block Module using composer gives me this error.
![error](https://user-images.githubusercontent.com/12660951/28161971-f8a80d40-67de-11e7-8692-ec5b7ae4c11d.png)

**Comment by nWidart** [comment]
That's probably because you try to install 2.0 on asgardcms 1.0, or vice versa.

**Comment by ikashifullah** [comment]
Thank you, @nWidart for your quick reply, but I am using asgardcms 2.0, but I don't know about Block Module, I just used this command to install, 
composer require asgardcms/block.

Could you please guide me how to fix it now?

**Comment by ikashifullah** [comment]
Also, if this is the case, that I am using asgardcms 1.0, then how to install asgardcms 2.0, the reason I am asking is that I just used this command to install asgardcms:

_composer create-project asgardcms/platform your-project-name_

**Comment by nWidart** [comment]
that command will install 2.0. You can confirm this by checking the version in the bottom right, on the backend.

You need to require version 2.0 for block module.

**Comment by ikashifullah** [comment]
Thank you, for quick info, it's confirmed that I am using asgardcms 2.0
![asgardcms](https://user-images.githubusercontent.com/12660951/28162477-9c92b2ec-67e0-11e7-82e8-99342d080ea9.png)

**Comment by ikashifullah** [comment]
@nWidart, I have solved the issue by appending version to the package as:

`composer require asgardcms/block:2.0.x-dev`

Thank you for amazing Laravel CMS!

**Comment by nWidart** [comment]
Awesome! 👍 

I will tag this 2.0 so it's easier to install as soon as I have some time. 😄

**Comment by nWidart** [comment]
2.0 was tagged.

**Comment by ikashifullah** [comment]
Thank you, @nWidart.

Keep up the good work!
