### ISSUE TITLE
can't install module with php5.6

### ISSUE THREAD

**Issue by okochunk** [AsgardCms/Block#21]
why block modules not support for php < 7 ? always got this 
  Problem 1
    - idavoll/core-module 3.0.x-dev requires php >=7.0.0 -> your PHP version (5.6.27) does not satisfy that requirement.
    - idavoll/core-module 3.0.x-dev requires php >=7.0.0 -> your PHP version (5.6.27) does not satisfy that requirement.
    - asgardcms/block 3.0.0 requires idavoll/core-module ~3.0 -> satisfiable by idavoll/core-module[3.0.x-dev].
    - Installation request for asgardcms/block ^3.0 -> satisfiable by asgardcms/block[3.0.0].

**Comment by nWidart** [comment]
That's normal, it requires php 7 since version 3.

**Comment by okochunk** [comment]
how with user still use version 2 ?

**Comment by nWidart** [comment]
By using composer. Look up the composer documentation for this.

**Comment by okochunk** [comment]
awesome. great thanks, btw http://forum.asgardcms.com/ is 502 (bad gateway)

**Comment by nWidart** [comment]
Oh thanks for the forum, I've started it up again.
