### ISSUE TITLE
Module translation in permission view

### ISSUE THREAD

**Issue by Fisiu** [AsgardCms/Block#22]
How to enable translations of fields under Group permission view?
![image](https://user-images.githubusercontent.com/33876/37629714-a8a6043e-2be0-11e8-9060-5129fc01b2e8.png)

**Comment by nWidart** [comment]
Hello,

I don't believe this module has been updated to the latest version of asgardcms. Which is causing the issue you see there.

I would accept a pull request where the upgrade has been done. 😄

**Comment by nWidart** [comment]
Nevermind I see it has been upgraded and the permissions look correct.

What version of the block module are you using?

**Comment by Fisiu** [comment]
It seems translation was not handled by ServiceProvider. #23 should address this issue.

**Comment by Fisiu** [comment]
PR merged, issue solved. I'm closing.
