### ISSUE TITLE
where am I supposed to add the {!! Block::get('block-name') !!} ?

### ISSUE THREAD

**Issue by icetimux** [AsgardCms/Block#7]
Hi, where am I supposed to add the {!! Block::get('block-name') !!} ? is it in the ckeditor? when I do it in the ckeditor it doesnt work, just comes out as {!! Block::get('block-name') !!}

Note: im trying it out on the demo site of asgard

**Comment by nWidart** [comment]
Hello, 

You can use that in the views itself. It wasn't made for usage inside ckeditor. It probably could be enhanced for that be I didn't have that requirement at the time.
